<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net45</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ic4dotnet" Version="1.5.0.3306" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\common\ConsoleHelper\ConsoleHelper.csproj" />
  </ItemGroup>

</Project>
