<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <ApplicationIcon>tis.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="tis.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ic4dotnet" Version="1.5.3.3316" />
    <PackageReference Include="ic4dotnet.System.Drawing" Version="1.5.3.3316" />
    <PackageReference Include="ic4dotnet.System.Windows.Forms" Version="1.5.3.3316" />
  </ItemGroup>

</Project>